"""Add first_name and last_name to users

Revision ID: 88403c4ba229
Revises: 
Create Date: 2025-02-09 02:17:08.091930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88403c4ba229'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seen_assignments')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_table('users')
    op.drop_table('notification_settings')
    op.drop_table('sent_reminders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_reminders',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'assignment_id', 'interval', name='_user_assignment_interval_uc')
    )
    op.create_table('notification_settings',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'interval', name='_user_notification_uc')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name='users_pkey')
    )
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('seen_assignments',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'assignment_id', name='_user_assignment_uc')
    )
    # ### end Alembic commands ###
